packages:
  - .
  - apps/*

onlyBuiltDependencies:
  - electron

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  electron: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
