packages:
  - .
  - apps/*

onlyBuiltDependencies:
  - electron

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  electron: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
