packages:
  - .
  - apps/*

onlyBuiltDependencies:
  - electron

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  electron: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - poyraz-ui@3.0.0
  - poyraz-ui@3.0.1
  - poyraz-ui@3.0.2
